//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADFSDPhamaV2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int order_id { get; set; }
        public int medication_id { get; set; }
        public int price { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Medication Medication { get; set; }
        public virtual Order Order { get; set; }
    }
}
